version: '3.9'

networks:
  common_network:

services:
  php-apache:
    container_name: 'gainey-website'
    build:
      context: ./docker54
      dockerfile: Dockerfile
    ports:
    - '${APP_PORT:-80}:80'
    volumes:
      - '.:/var/www'
    networks:
      - common_network
  mariadb:
    container_name: 'gainey-mariadb'
    image: mariadb:10
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - common_network
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    container_name: 'gainey-phpmyadmin'
    image: phpmyadmin
    ports:
      - '${PMA_PORT:-81}:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - UPLOAD_LIMIT=100M
      - MAX_EXECUTION_TIME=600
      - MEMORY_LIMIT=2G
    networks:
      - common_network       
volumes:
  db_data: